// ? 1332. Remove Palindromic Subsequences
// ! Link: https://leetcode.com/problems/remove-palindromic-subsequences/

// ? You are given a string s consisting only of letters 'a' and 'b'. In a single
// ? step you can remove one palindromic subsequence from s. Return the minimum 
// ? number of steps to make the given string empty.

// ? A string is a subsequence of a given string if it is generated by deleting some 
// ? characters of a given string without changing its order. Note that a subsequence 
// ? does not necessarily need to be contiguous. A string is called palindrome if is 
// ? one that reads the same backward as well as forward.

// * Input: s = "ababa" ===> Output: 1 (isPalindrome)
// * Input: s = "abb" ===> Output: 2 (isNotPalindrome)

var removePalindromeSub = function(s) {
  let left = 0;
  let right = s.length - 1;

  while (left < right) {
    if (s[left] !== s[right]) {
      return 2;
    }
      
    left++
    right--
  }

  return 1;
};